### ISSUE TITLE
Support aliases for colors

### ISSUE THREAD

**Issue by frycz** [component-driven/react-design-tokens#11]
Now, colors palettes are enumerated from `0` to `palette.length - 1`.

<img src="https://user-images.githubusercontent.com/6745392/78532965-68a54100-77e8-11ea-96e6-53f7f31b1456.png" width=100 />

We want to support aliases for color arrays indices.

Example:

```jsx
const colors = ['#aaa', '#bbb', '#bbb']
colors.aliases = ['default', 'active', 'disabled']

<PaletteSwatch token={"gray"} value={colors} aliasesKey='aliases' />
```

or

```jsx
<ColorSwatch token={"error"} value={"#C0100F"} alias={"red"} />
```

### Proposal

- extend `ColorSwatch` with `alias` property and display alias under the default name

<img src="https://user-images.githubusercontent.com/6745392/78531417-a2c11380-77e5-11ea-87cf-621aa5ff4059.png" width=100 />

- extend `PaletteSwatch` with `aliasesKey` prop which will be used to read aliases from colors array and pass it to `ColorSwatch`

**Comment by okonet** [comment]
Although I'm not sure that's how I would structure colors section in the theme but I'd happy to get support for aliases on all tokens since it's supported by the spec.

**Comment by frycz** [comment]
@okonet  By structuring the colors section do you mean the position of the alias name?

Should we add support for all aliases in a separate issue?

**Comment by okonet** [comment]
> By structuring the colors section

No, I meant I would not not use aliases like you're using so I would not run into that problem in the first place. Usually, what I do is having palettes (no semantics) and then I _refer_ to them in the color theme to get more "semantic" tokens like "warning" etc.

Example https://github.com/component-driven/react-design-tokens/blob/f175059fdc27c57e3ac17b9141e5cc92517bbab4/src/examples/cdds.js#L48-L49

**Comment by okonet** [comment]
> Should we add support for all aliases in a separate issue?

I don't think so but I think the PR should include aliases support for all scales. Thoughts?

**Comment by frycz** [comment]
This is how we use aliases in our DS. Colors array has `aliases` prop. The PR includes support for all scales :-) Or you mean tokens?
