### ISSUE TITLE
Provide a better way for setting styles

### ISSUE THREAD

**Issue by frycz** [component-driven/react-design-tokens#15]
Currently, user needs to update the theme to change font sizes in the `Colors` component:

```jsx
const extendedTheme = {
    ...theme,
    fontSizes: {
        ...theme.fontSizes,
        sm: 14,
        xs: 14,
    }
}

<Colors theme={extendedTheme} />
```

**Comment by okonet** [comment]
So the idea of this repo was to allow swatches to use the project's theme. Unfortunately styled-system theme spec allows polymorphic values for scales (arrays and objects) so it's not clear how to standardize those.

One idea could be to have a default theme that can be overridden. What's your thoughts on it?
